[package]
name = "cloudpaste"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker = "0.0.9"
serde_json = "1"
rand = "0.8"
getrandom = { version = "*", features = ["js", "wasm-bindgen"] }
console_error_panic_hook = "0.1"
